services:
  php:
    build: php
    restart: always
    volumes:
      - ${APPLICATION_PATH}:/var/www/html

  composer:
    image: composer
    volumes:
      - ${APPLICATION_PATH}:/app

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - php:php